
source:      .
destination: ./_site
plugins:     ./_plugins

paginate: 10

safe:        false
auto:        false
server:      false
server_port: 4000
base-url:    /


future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   pretty  

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex