source:      .
destination: ./_site
plugins:     ./_plugins

paginate: 10

safe:        false
auto:        false
server:      false
server_port: 4000
base-url:    /


future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   pretty  